-- CREATE TABLE WITH AUTO INCREMENT
CREATE TABLE PRO01 (
  O01F01 INT PRIMARY KEY AUTO_INCREMENT COMMENT "Product ID",
  O01F02 VARCHAR(50) NOT NULL COMMENT "Product Name",
  O01F03 DECIMAL(10,2) COMMENT "Product Price"
)AUTO_INCREMENT = 100;